### ISSUE TITLE
Add kenny.nl

### ISSUE THREAD

**Issue by brean** [jstaerk/didakten#2]
I like the kenny.nl assets. Most of them are CC-licensed. They are mostly 2d but also 3d and even some sounds, so I am not sure where to put this in your list otherwise I would directly provide a PR.

**Comment by jstaerk** [comment]
good one, thanks.  For the time being I only added them in "other people's lists" but that might change when I have time to go through them one by one

**Comment by brean** [comment]
There are some very cool "other people's lists" you found there!
